{{ range .nerdFonts.fonts }}
["nerd-font-{{ . }}"]
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ $.nerdFonts.version }}/{{ . }}.zip"
include = ["*.ttf", "*.otf"]
targetPath = ".local/share/fonts"
{{ end }}

{{- if eq .chezmoi.os "linux" }}
{{- $release := gitHubLatestRelease "jesseduffield/lazygit" }}
{{- $version := trimPrefix "v" ($release.TagName | toString) }}
{{- $asset := printf "lazygit_%s_linux_x86_64.tar.gz" $version }}

[".local/bin/lazygit"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "jesseduffield/lazygit" $asset | quote }}
path = "lazygit"
executable = true
{{- end }}

{{- if eq .chezmoi.os "linux" }}

[".oh-my-zsh"]
type = "archive"
url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"

[".oh-my-zsh/custom/themes/powerlevel10k"]
type = "archive"
url = "https://github.com/romkatv/powerlevel10k/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"

{{- end }}
